name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push
        uses: mr-smithers-excellent/docker-build-push@v6.3
        with:
          push: true
          image: fhir-server
          registry: ghcr.io
          githubOrg: ikmdev
          addLatest: true
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
